app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_article:
    resource: "@AppBundle/Controller/ArticleController.php"
    type: rest