services:
    bankmaster.tour.get_one:
        class: AppBundle\Fulcrum\Usecase\GetOne
        arguments: ["@bankmaster.tour_repository"]
        
    bankmaster.tour.search:
        class: AppBundle\Fulcrum\Usecase\Search
        arguments: ["@bankmaster.tour_repository"]
        
    bankmaster.tour.create:
        class: AppBundle\Fulcrum\Usecase\CreateEntity
        arguments: ["@bankmaster.tour_repository", "@event_dispatcher"]
        
    bankmaster.tour.update:
        class: AppBundle\Fulcrum\Usecase\UpdateEntity
        arguments: ["@bankmaster.tour_repository", "@event_dispatcher"]
        
    bankmaster.tour.remove:
        class: AppBundle\Fulcrum\Usecase\RemoveEntity
        arguments: ["@bankmaster.tour_repository", "@event_dispatcher"]
        
        
    bankmaster.tour_repository:
        class:  AppBundle\Repository\TourRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Tour
            
    bankmaster.send_mail:
        class:  AppBundle\Usecase\SendMail
        arguments: ["@swiftmailer.mailer.default"]
        